

// book Creation 

POST http://127.0.0.1:5555/books HTTP/1.1
Content-Type: application/json

{
    "title": "hellow world ",
    "author": "Nice people",
    "publishYear": "1800"
}

#####################################
//Server Test
GET http://127.0.0.1:5555 HTTP/1.1

######
//Get all books 
GET http://127.0.0.1:5555/books HTTP/1.1  


#####
//Get book by id 
GET http://127.0.0.1:5555/books/653fed467d71c371c5e32509 HTTP/1.1

###
PUT http://127.0.0.1:5555/books/65405496437c584bc80e183e HTTP/1.1
Content-Type: application/json

{
    "title": "Machine learning algorithms",
    "author": "Ed sherran",
    "publishYear": "2023"
}


#####
//delete book 

DELETE http://127.0.0.1:5555/books/653fed467d71c371c5e32509 HTTP/1.1